[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
